# Generated by Django 5.0.4 on 2026-02-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Academy',
        ),
    ]
