# Generated by Django 5.1.6 on 2026-04-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('coach', 'Coach'), ('academy_owner', 'Academy owner')], default='user', max_length=20),
        ),
    ]
