# Generated by Django 5.0.4 on 2026-02-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
