# Generated by Django 5.1.6 on 2026-03-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0002_academy_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwimmingPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.JSONField(blank=True, default=list)),
                ('dimension', models.JSONField(blank=True, default=list)),
                ('heated', models.BooleanField(default=False)),
                ('showers', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='swimming_pools/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimming_pools', to='academie.academy')),
            ],
        ),
    ]
