# Generated by Django 5.1.6 on 2026-04-22 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0003_swimmingpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='academies/'),
        ),
        migrations.AddField(
            model_name='academy',
            name='specialities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='academie.academy')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('academy', 'day')},
            },
        ),
    ]
