# Generated by Django 5.1.6 on 2026-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0004_academy_picture_academy_specialities_openinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='academy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
