# Generated by Django 5.0.4 on 2026-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0006_academy_owner_course_coursetiming_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
