# Generated by Django 5.1.6 on 2026-05-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academie', '0010_academy_monthly_price_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
